"""G4 v4: fixed-size single-cell traction on an initially random collagen network.

This generation deliberately imports the validated random geometry and elastic
solver from G4 v3 instead of copying or overwriting them.  It separates two
central objects that looked similar in the old animation but answer different
questions:

* ``run_cavity_benchmark`` is a prescribed contracting *cavity*.  It tests the
  collagen network mechanics and is not a biological model of a shrinking cell.
* every biological-cell run keeps the cell radius fixed.  Continued force is
  generated by actin--clutch loading, not by changing the cell radius.

Units are micrometre (um), nanonewton (nN), and second (s).  Crosslinks are
permanent elastic material-point links.  There is no SLS, Brownian force,
plasticity, crosslink rupture, cell growth, or spheroid biology in this module.
"""

from __future__ import annotations

from collections import deque
from dataclasses import asdict, dataclass, replace
import math
from typing import Literal

import numpy as np

from generations.g2_corrected.common.model import ContactPatch, NetworkSpec
from generations.g4_interactive_calibration.model import patch_point
from generations.g4_v2_multiscale.model import (
    ActiveMapper,
    FastStepper,
    _counter_uniform_vector,
)
from generations.g4_v3_random_to_aligned.model import (
    G4V3Config,
    build_random_network,
    elastic_energy_by_fiber,
    graph_distance_from_contact,
    make_random_void_spec,
    run_fixed_cell_passive_check,
    run_prescribed_contraction,
    surface_contact_patches,
)


TractionGeometry = Literal["normal", "dipole"]
ClutchMode = Literal["independent", "shared"]


@dataclass(frozen=True)
class G4V4Config(G4V3Config):
    """Configuration for cumulative G4 v4 A--D experiments.

    The 10 um radius and effective clutch constants are inherited provisional
    assumptions.  They are exposed here so every generated result carries its
    parameter ledger.  Durations follow the Riching et al. observation clocks:
    two hours for single-cell collagen displacement and six hours for migration.
    """

    fixed_duration: float = 7200.0
    fixed_sample_interval: float = 240.0
    migration_duration: float = 21600.0
    migration_sample_interval: float = 600.0
    event_sample_interval_v4: float = 0.10
    event_half_window_v4: float = 10.0
    dipole_axis_angle: float = 0.0
    dipole_half_width: float = math.pi / 6.0
    minimum_event_time: float = 30.0
    clutch_mode: ClutchMode = "shared"
    radius_check_values: tuple[float, ...] = (8.0, 10.0, 12.0)
    source_system: str = "MDA-MB-231 single cell; mechanism-first calibration"

    def validate(self) -> None:
        super().validate()
        if self.fixed_duration <= 0.0 or self.migration_duration <= 0.0:
            raise ValueError("biological observation durations must be positive")
        if self.fixed_sample_interval < self.dt or self.migration_sample_interval < self.dt:
            raise ValueError("observation intervals must be at least dt")
        if self.event_sample_interval_v4 < self.dt:
            raise ValueError("event sampling must be at least dt")
        if not 0.0 < self.dipole_half_width < 0.5 * math.pi:
            raise ValueError("dipole_half_width must be between 0 and pi/2")
        if any(radius <= 0.0 for radius in self.radius_check_values):
            raise ValueError("radius-check values must be positive")
        if self.clutch_mode not in ("independent", "shared"):
            raise ValueError("clutch_mode must be independent or shared")


@dataclass
class V4ClutchState:
    """Effective clutches at every collagen material-point site.

    ``extension`` stores each bound-clutch extension in the independent
    control. ``site_extension`` stores the common extension of the primary
    equal-load-sharing cluster.
    """

    bound: np.ndarray
    extension: np.ndarray
    site_extension: np.ndarray
    cumulative_ruptures: int = 0
    cumulative_site_failures: int = 0


def _copy_patch(patch: ContactPatch, *, weight: float | None = None) -> ContactPatch:
    return ContactPatch(
        fiber=int(patch.fiber),
        edge=int(patch.edge),
        alpha=float(patch.alpha),
        point=np.asarray(patch.point, dtype=float).copy(),
        surface_distance=float(patch.surface_distance),
        weight=float(patch.weight if weight is None else weight),
        normal_in=np.asarray(patch.normal_in, dtype=float).copy(),
    )


def _normalize_patch_weights(patches: list[ContactPatch]) -> list[ContactPatch]:
    if not patches:
        return []
    weights = np.asarray([max(float(p.weight), 0.0) for p in patches])
    if float(weights.sum()) <= 0.0:
        weights[:] = 1.0
    weights /= weights.sum()
    return [_copy_patch(patch, weight=float(weight)) for patch, weight in zip(patches, weights)]


def select_force_geometry(
    network,
    center: np.ndarray,
    geometry: TractionGeometry,
    cfg: G4V4Config,
) -> list[ContactPatch]:
    """Return eligible contact-band points for normal or dipole traction.

    The normal case uses every natural collagen contact.  The dipole control
    retains two opposite angular sectors around ``dipole_axis_angle``.  Both
    cases renormalize the same Gaussian surface-distance weights so the total
    requested force, not the number of retained contacts, is controlled.
    """

    candidates = surface_contact_patches(network, center)
    if geometry == "normal":
        return _normalize_patch_weights(candidates)
    if geometry != "dipole":
        raise ValueError("geometry must be 'normal' or 'dipole'")
    axis = np.asarray([math.cos(cfg.dipole_axis_angle), math.sin(cfg.dipole_axis_angle)])
    cutoff = math.cos(cfg.dipole_half_width)
    selected: list[ContactPatch] = []
    scores: list[float] = []
    for patch in candidates:
        point = patch_point(network, patch)
        outward = point - center
        outward /= max(float(np.linalg.norm(outward)), 1e-12)
        score = abs(float(outward @ axis))
        if score >= cutoff:
            selected.append(patch)
            scores.append(score)
    if len(selected) < 2 and candidates:
        ranked = sorted(
            candidates,
            key=lambda patch: abs(
                float(
                    ((patch_point(network, patch) - center)
                     / max(float(np.linalg.norm(patch_point(network, patch) - center)), 1e-12))
                    @ axis
                )
            ),
            reverse=True,
        )
        selected = ranked[: min(2, len(ranked))]
        scores = [1.0] * len(selected)
    weighted = [
        _copy_patch(patch, weight=float(patch.weight) * max(score, 1e-12))
        for patch, score in zip(selected, scores)
    ]
    return _normalize_patch_weights(weighted)


def _contact_tangent(network, patch: ContactPatch) -> np.ndarray:
    i, j = network.edges[patch.edge]
    tangent = network.r[j] - network.r[i]
    return tangent / max(float(np.linalg.norm(tangent)), 1e-12)


def decompose_contact_forces(network, patches, vectors) -> tuple[np.ndarray, np.ndarray]:
    """Resolve each cell traction vector parallel/perpendicular to its fibre."""

    vectors = np.asarray(vectors, dtype=float)
    parallel = np.zeros_like(vectors)
    for index, patch in enumerate(patches):
        tangent = _contact_tangent(network, patch)
        parallel[index] = float(vectors[index] @ tangent) * tangent
    return parallel, vectors - parallel


def _fiber_orientation_angles(network, center: np.ndarray) -> tuple[np.ndarray, np.ndarray]:
    """Segment angles relative to radial and boundary-tangent directions."""

    radial_angles: list[float] = []
    boundary_angles: list[float] = []
    for ids in network.fibers:
        a = network.r[ids[:-1]]
        b = network.r[ids[1:]]
        tangent = b - a
        tangent /= np.maximum(np.linalg.norm(tangent, axis=1), 1e-12)[:, None]
        midpoint = 0.5 * (a + b)
        radial = midpoint - center
        radial /= np.maximum(np.linalg.norm(radial, axis=1), 1e-12)[:, None]
        boundary = np.column_stack([-radial[:, 1], radial[:, 0]])
        radial_angles.extend(np.arccos(np.clip(np.abs(np.sum(tangent * radial, axis=1)), 0.0, 1.0)))
        boundary_angles.extend(np.arccos(np.clip(np.abs(np.sum(tangent * boundary, axis=1)), 0.0, 1.0)))
    return np.asarray(radial_angles), np.asarray(boundary_angles)


def _radial_order_centered(
    network,
    center: np.ndarray,
    shells: tuple[tuple[float, float], ...] = ((0.0, 10.0), (10.0, 25.0), (25.0, 50.0)),
) -> np.ndarray:
    """Signed radial order in shells measured from the current cell surface."""

    i, j = network.edges.T
    segment = network.r[j] - network.r[i]
    tangent = segment / np.maximum(np.linalg.norm(segment, axis=1), 1e-12)[:, None]
    midpoint = 0.5 * (network.r[i] + network.r[j])
    radial = midpoint - center
    radius = np.linalg.norm(radial, axis=1)
    radial /= np.maximum(radius, 1e-12)[:, None]
    value = 2.0 * np.square(np.sum(tangent * radial, axis=1)) - 1.0
    surface = radius - network.cfg.cell_radius
    return np.asarray([
        float(np.mean(value[(surface >= low) & (surface < high)]))
        if np.any((surface >= low) & (surface < high)) else float("nan")
        for low, high in shells
    ])


def _radial_by_fiber_centered(network, center: np.ndarray) -> np.ndarray:
    values = np.empty(len(network.fibers))
    for fid, ids in enumerate(network.fibers):
        a = network.r[ids[:-1]]
        b = network.r[ids[1:]]
        tangent = b - a
        tangent /= np.maximum(np.linalg.norm(tangent, axis=1), 1e-12)[:, None]
        midpoint = 0.5 * (a + b)
        radial = midpoint - center
        radial /= np.maximum(np.linalg.norm(radial, axis=1), 1e-12)[:, None]
        values[fid] = float(np.mean(2.0 * np.square(np.sum(tangent * radial, axis=1)) - 1.0))
    return values


def _graph_class_metrics_centered(network, distance, initial_radial_by_fiber, center):
    bead_displacement = np.linalg.norm(network.r - network.r0, axis=1)
    fiber_displacement = np.asarray([
        float(np.mean(bead_displacement[ids])) for ids in network.fibers
    ])
    delta = _radial_by_fiber_centered(network, center) - initial_radial_by_fiber
    masks = {
        "direct": distance == 0,
        "one_hop": distance == 1,
        "two_plus": distance >= 2,
        "unconnected": distance < 0,
    }
    return {
        label: {
            "n": int(mask.sum()),
            "mean_displacement": float(np.mean(fiber_displacement[mask])) if np.any(mask) else 0.0,
            "mean_delta_radial_order": float(np.mean(delta[mask])) if np.any(mask) else 0.0,
        }
        for label, mask in masks.items()
    }


def _relative_substrate_speeds(
    network, velocity, patches, center, cell_velocity
) -> np.ndarray:
    """ECM material-point speed relative to the cell along clutch loading.

    Actin speed is defined in the cell frame. After releasing the cell the
    substrate term must therefore use ``v_ECM - v_cell``; otherwise rigid cell
    translation would be misread as additional clutch extension.
    """

    values = np.zeros(len(patches))
    for site, patch in enumerate(patches):
        point = patch_point(network, patch)
        inward = center - point
        inward /= max(float(np.linalg.norm(inward)), 1e-12)
        i, j = network.edges[patch.edge]
        material_velocity = (1.0 - patch.alpha) * velocity[i] + patch.alpha * velocity[j]
        values[site] = float((material_velocity - cell_velocity) @ inward)
    return values


def _substrate_speeds(network, velocity, patches, center) -> np.ndarray:
    """Backward-compatible fixed-cell form of the relative-speed helper."""

    return _relative_substrate_speeds(
        network, velocity, patches, center, np.zeros(2, dtype=float)
    )


def cell_velocity_from_ecm_forces(forces: np.ndarray, cell_drag: float) -> np.ndarray:
    """Overdamped cell velocity from the equal-and-opposite ECM reaction."""

    if cell_drag <= 0.0:
        raise ValueError("cell_drag must be positive")
    forces = np.asarray(forces, dtype=float)
    return -forces.sum(axis=0) / cell_drag if forces.size else np.zeros(2)


def _bending_change(network) -> np.ndarray:
    """Magnitude of discrete curvature-vector change at interior beads."""

    values: list[np.ndarray] = []
    for ids in network.fibers:
        if len(ids) < 3:
            continue
        current = network.r[ids[:-2]] - 2.0 * network.r[ids[1:-1]] + network.r[ids[2:]]
        initial = network.r0[ids[:-2]] - 2.0 * network.r0[ids[1:-1]] + network.r0[ids[2:]]
        values.append(np.linalg.norm(current - initial, axis=1))
    return np.concatenate(values) if values else np.zeros(0)


def _v4_frame(
    network,
    center,
    time,
    patches,
    vectors,
    distance,
    initial_shell,
    initial_radial_by_fiber,
    *,
    cell_radius,
    requested_force=0.0,
    bound=None,
    extension=None,
    site_force=None,
    actin_speed=None,
    substrate_speed=None,
    cumulative_ruptures=0,
    cumulative_site_failures=0,
) -> dict:
    """Create one auditable physics/visualization frame."""

    _, _, _, energy, bond_strain, crosslink_force = network.elastic_forces(True)
    stretch_by_fiber, bend_by_fiber = elastic_energy_by_fiber(network)
    points = np.asarray([patch_point(network, patch) for patch in patches], dtype=float)
    vectors = np.asarray(vectors, dtype=float)
    parallel, perpendicular = decompose_contact_forces(network, patches, vectors)
    guidance = np.asarray([_contact_tangent(network, patch) for patch in patches], dtype=float)
    for index, point in enumerate(points):
        outward = point - center
        if float(guidance[index] @ outward) < 0.0:
            guidance[index] *= -1.0
    radial_angles, boundary_angles = _fiber_orientation_angles(network, np.asarray(center))
    shell = _radial_order_centered(network, np.asarray(center))
    reaction = -vectors.sum(axis=0) if len(vectors) else np.zeros(2)
    return {
        "time": float(time),
        "positions": network.r.copy(),
        "center": np.asarray(center, dtype=float).copy(),
        "cell_radius": float(cell_radius),
        "contact_points": points,
        "contact_vectors": vectors.copy(),
        "force_parallel": parallel,
        "force_perpendicular": perpendicular,
        "local_guidance_direction": guidance,
        "parallel_magnitude": float(np.linalg.norm(parallel, axis=1).sum()),
        "perpendicular_magnitude": float(np.linalg.norm(perpendicular, axis=1).sum()),
        "requested_force": float(requested_force),
        "distributed_force": float(np.linalg.norm(vectors, axis=1).sum()),
        "cell_reaction": reaction,
        "force_balance_error": float(np.linalg.norm(vectors.sum(axis=0) + reaction)),
        "radial_order_by_shell": shell,
        "delta_radial_order_by_shell": shell - initial_shell,
        "mean_radial_angle_deg": float(np.degrees(np.mean(radial_angles))),
        "mean_boundary_angle_deg": float(np.degrees(np.mean(boundary_angles))),
        "energy": dict(energy),
        "stretch_to_bend_ratio": float(energy["stretch"] / max(energy["bend"], 1e-18)),
        "recruited_fraction": float(np.mean(stretch_by_fiber > bend_by_fiber)),
        "bond_strain": bond_strain.copy(),
        "bending_change": _bending_change(network),
        "crosslink_force": crosslink_force.copy(),
        "graph_class_metrics": _graph_class_metrics_centered(
            network, distance, initial_radial_by_fiber, np.asarray(center)
        ),
        "bound": None if bound is None else np.asarray(bound, dtype=np.uint8).copy(),
        "extension": None if extension is None else np.asarray(extension, dtype=float).copy(),
        "site_force": None if site_force is None else np.asarray(site_force, dtype=float).copy(),
        "actin_speed": None if actin_speed is None else np.asarray(actin_speed, dtype=float).copy(),
        "substrate_speed": None if substrate_speed is None else np.asarray(substrate_speed, dtype=float).copy(),
        "cumulative_ruptures": int(cumulative_ruptures),
        "cumulative_site_failures": int(cumulative_site_failures),
    }


def run_fixed_cell_passive(
    cfg: G4V4Config = G4V4Config(), *, spec: NetworkSpec | None = None
) -> dict:
    """G4 v4-A biological negative control: fixed-size cell, zero traction."""

    result = run_fixed_cell_passive_check(cfg, spec=spec)
    result["central_object"] = "fixed biological cell"
    result["cell_radius_constant"] = True
    return result


def run_cavity_benchmark(
    cfg: G4V4Config = G4V4Config(),
    *,
    contraction: float = 0.20,
    spec: NetworkSpec | None = None,
    crosslink_probability: float = 1.0,
) -> dict:
    """G4 v4-A mechanics benchmark; the contracting object is not a cell."""

    result = run_prescribed_contraction(
        cfg,
        contraction=contraction,
        spec=spec,
        crosslink_probability=crosslink_probability,
    )
    result["central_object"] = "contractile cavity/inclusion"
    result["biological_cell_model"] = False
    return result


def run_fixed_force_direction(
    cfg: G4V4Config = G4V4Config(),
    *,
    geometry: TractionGeometry = "normal",
    total_force: float | None = None,
    duration: float | None = None,
    sample_interval: float | None = None,
    spec: NetworkSpec | None = None,
    crosslink_probability: float | None = None,
) -> dict:
    """G4 v4-B: fixed-size cell with deterministic contact-band traction."""

    cfg.validate()
    force = cfg.total_pull_force if total_force is None else float(total_force)
    run_time = cfg.fixed_duration if duration is None else float(duration)
    observe = cfg.fixed_sample_interval if sample_interval is None else float(sample_interval)
    probability = cfg.crosslink_probability if crosslink_probability is None else float(crosslink_probability)
    network, spec, report = build_random_network(
        cfg, spec=spec, crosslink_probability=probability
    )
    center = np.zeros(2)
    patches = select_force_geometry(network, center, geometry, cfg)
    if not patches:
        raise RuntimeError("random network has no eligible cell-surface material points")
    direct = [int(patch.fiber) for patch in patches]
    distance = graph_distance_from_contact(network, direct)
    initial_shell = _radial_order_centered(network, center)
    initial_radial_by_fiber = _radial_by_fiber_centered(network, center)
    stepper = FastStepper(network)
    mapper = ActiveMapper(network, patches)
    nsteps = int(round(run_time / cfg.dt))
    every = max(1, int(round(observe / cfg.dt)))
    frames: list[dict] = []
    vectors = np.zeros((len(patches), 2))

    for step in range(nsteps + 1):
        time = step * cfg.dt
        ramp = min(1.0, time / max(cfg.force_ramp_time, cfg.dt))
        requested = force * ramp
        active, _, vectors = mapper.map(requested, center, weighted=True)
        if step % every == 0 or step == nsteps:
            frames.append(
                _v4_frame(
                    network,
                    center,
                    time,
                    patches,
                    vectors,
                    distance,
                    initial_shell,
                    initial_radial_by_fiber,
                    cell_radius=cfg.cell_radius,
                    requested_force=requested,
                )
            )
        if step == nsteps:
            break
        stepper.step(active, center, cfg.dt)

    return {
        "config": asdict(cfg),
        "spec": spec,
        "network": network,
        "report": report,
        "mode": "fixed-force",
        "geometry": geometry,
        "frames": frames,
        "patches": patches,
        "direct_fibers": direct,
        "graph_distance": distance,
        "cell_radius_constant": bool(
            all(abs(frame["cell_radius"] - cfg.cell_radius) < 1e-12 for frame in frames)
        ),
        "max_displacement": float(np.max(np.linalg.norm(network.r - network.r0, axis=1))),
        "final_delta_radial_order_by_shell": frames[-1]["delta_radial_order_by_shell"].copy(),
        "final_graph_class_metrics": frames[-1]["graph_class_metrics"],
    }


def _clutch_uniforms(cfg: G4V4Config, step: int, channel: int, n_sites: int) -> np.ndarray:
    values = _counter_uniform_vector(
        cfg.counter_seed,
        step,
        channel,
        n_sites * cfg.n_clutches_per_site,
    )
    return values.reshape(n_sites, cfg.n_clutches_per_site)


def _advance_clutches(cfg, state, substrate_speed, step):
    """One load--rupture--rebind update for independent or shared clutches."""

    before_count = state.bound.sum(axis=1)
    if cfg.clutch_mode == "shared":
        site_stiffness = cfg.n_clutches_per_site * cfg.clutch_stiffness
        traction_before = np.where(
            before_count > 0, site_stiffness * state.site_extension, 0.0
        )
    else:
        force_before = cfg.clutch_stiffness * state.extension * state.bound
        traction_before = force_before.sum(axis=1)
    actin_speed = cfg.unloaded_actin_speed * np.maximum(
        0.0, 1.0 - traction_before / cfg.motor_stall_per_site
    )
    relative_speed = np.maximum(0.0, actin_speed - substrate_speed)
    if cfg.clutch_mode == "shared":
        state.site_extension[before_count > 0] += cfg.dt * relative_speed[before_count > 0]
        site_force_before = np.where(
            before_count > 0, site_stiffness * state.site_extension, 0.0
        )
        per_clutch_force = np.divide(
            site_force_before,
            np.maximum(before_count, 1),
            dtype=float,
        )[:, None]
        per_clutch_force = np.repeat(
            per_clutch_force, cfg.n_clutches_per_site, axis=1
        )
    else:
        increment = cfg.dt * np.repeat(
            relative_speed[:, None], cfg.n_clutches_per_site, axis=1
        )
        state.extension[state.bound] += increment[state.bound]
        per_clutch_force = cfg.clutch_stiffness * state.extension
    off_rate = cfg.clutch_off_rate0 * np.exp(
        np.minimum(np.abs(per_clutch_force) / cfg.bell_force, 50.0)
    )
    u_off = _clutch_uniforms(cfg, step, 1, len(state.bound))
    ruptures = state.bound & (u_off < 1.0 - np.exp(-off_rate * cfg.dt))
    state.bound[ruptures] = False
    state.extension[ruptures] = 0.0
    after_break_count = state.bound.sum(axis=1)
    site_failures = (before_count > 0) & (after_break_count == 0)
    state.site_extension[site_failures] = 0.0

    u_on = _clutch_uniforms(cfg, step, 0, len(state.bound))
    on_probability = 1.0 - math.exp(-cfg.clutch_on_rate * cfg.dt)
    binds = (~state.bound) & (u_on < on_probability)
    state.bound[binds] = True
    state.extension[binds] = 0.0

    state.cumulative_ruptures += int(ruptures.sum())
    state.cumulative_site_failures += int(site_failures.sum())
    after_count = state.bound.sum(axis=1)
    state.site_extension[after_count == 0] = 0.0
    if cfg.clutch_mode == "shared":
        total = np.where(after_count > 0, site_stiffness * state.site_extension, 0.0)
        shared = np.divide(total, np.maximum(after_count, 1), dtype=float)
        force = state.bound * shared[:, None]
        state.extension[:] = state.site_extension[:, None] * state.bound
    else:
        force = cfg.clutch_stiffness * state.extension * state.bound
    return (
        force.sum(axis=1),
        actin_speed,
        ruptures,
        binds,
        site_failures,
    )


def _angle_of_patch(network, patch, center) -> float:
    outward = patch_point(network, patch) - center
    return math.atan2(float(outward[1]), float(outward[0]))


def _relocate_failed_sites(network, center, patches, failures, cfg):
    """Relocate a fully detached site using its encountered fibre tangent.

    The outgoing direction is the local collagen tangent oriented away from
    the cell. The next site is the eligible surface material point nearest that
    direction. This is a declared contact-guidance rule: it uses no global
    polarization vector and it acts only after complete site failure.
    """

    if not np.any(failures):
        return patches
    fresh = select_force_geometry(network, center, "normal", cfg)
    if not fresh:
        return patches
    updated = [_copy_patch(patch) for patch in patches]
    used = {patch.fiber for index, patch in enumerate(updated) if not failures[index]}
    for site in np.flatnonzero(failures):
        old = updated[site]
        old_point = patch_point(network, old)
        old_outward = old_point - center
        old_outward /= max(float(np.linalg.norm(old_outward)), 1e-12)
        guidance = _contact_tangent(network, old)
        if float(guidance @ old_outward) < 0.0:
            guidance = -guidance
        available = [patch for patch in fresh if patch.fiber not in used] or fresh
        chosen = min(
            available,
            key=lambda patch: math.acos(
                np.clip(
                    float(
                        guidance
                        @ (
                            (patch_point(network, patch) - center)
                            / max(
                                float(np.linalg.norm(patch_point(network, patch) - center)),
                                1e-12,
                            )
                        )
                    ),
                    -1.0,
                    1.0,
                )
            ),
        )
        updated[site] = _copy_patch(chosen)
        used.add(chosen.fiber)
    return updated


def _event_snapshot(
    network,
    local_beads,
    center,
    time,
    patches,
    state,
    site_force,
    ruptures,
    binds,
    substrate_speed,
):
    return {
        "time": float(time),
        "positions": network.r[local_beads].copy(),
        "center": np.asarray(center).copy(),
        "contact_points": np.asarray([patch_point(network, p) for p in patches]),
        "bound": state.bound.astype(np.uint8).copy(),
        "extension": state.extension.copy(),
        "site_force": np.asarray(site_force).copy(),
        "ruptures": np.asarray(ruptures, dtype=np.uint8).copy(),
        "binds": np.asarray(binds, dtype=np.uint8).copy(),
        "substrate_speed": np.asarray(substrate_speed).copy(),
    }


def run_motor_clutch(
    cfg: G4V4Config = G4V4Config(),
    *,
    moving: bool = False,
    duration: float | None = None,
    sample_interval: float | None = None,
    spec: NetworkSpec | None = None,
    capture_event: bool = True,
) -> dict:
    """G4 v4-C/D: load--slip--recoil cycles with an optional released cell.

    The fixed-cell run uses the two-hour collagen-displacement clock.  The
    moving run uses the six-hour migration clock.  Contact material points are
    changed only after all clutches at a site have detached.
    """

    cfg.validate()
    run_time = (
        cfg.migration_duration if moving else cfg.fixed_duration
    ) if duration is None else float(duration)
    observe = (
        cfg.migration_sample_interval if moving else cfg.fixed_sample_interval
    ) if sample_interval is None else float(sample_interval)
    network, spec, report = build_random_network(cfg, spec=spec)
    center = np.zeros(2)
    patches = select_force_geometry(network, center, "normal", cfg)
    if not patches:
        raise RuntimeError("random network has no eligible clutch sites")
    direct = [int(patch.fiber) for patch in patches]
    distance = graph_distance_from_contact(network, direct)
    initial_shell = _radial_order_centered(network, center)
    initial_radial_by_fiber = _radial_by_fiber_centered(network, center)
    state = V4ClutchState(
        bound=np.zeros((len(patches), cfg.n_clutches_per_site), dtype=bool),
        extension=np.zeros((len(patches), cfg.n_clutches_per_site), dtype=float),
        site_extension=np.zeros(len(patches), dtype=float),
    )
    mapper = ActiveMapper(network, patches)
    stepper = FastStepper(network)
    substrate_speed = np.zeros(len(patches))
    site_force = np.zeros(len(patches))
    actin_speed = np.full(len(patches), cfg.unloaded_actin_speed)
    vectors = np.zeros((len(patches), 2))
    ruptures = np.zeros_like(state.bound)
    binds = np.zeros_like(state.bound)
    nsteps = int(round(run_time / cfg.dt))
    every = max(1, int(round(observe / cfg.dt)))
    event_every = max(1, int(round(cfg.event_sample_interval_v4 / cfg.dt)))
    half_frames = max(1, int(round(cfg.event_half_window_v4 / cfg.event_sample_interval_v4)))
    frames: list[dict] = []
    event_frames: list[dict] = []
    event_log: list[dict] = []
    ring: deque = deque(maxlen=half_frames + 1)
    event_time: float | None = None
    event_end: float | None = None
    # Event microscope: cell + full contact band + 2 um context. Full-field
    # overview frames remain separate, so the high-frequency clip does not
    # duplicate distant, visually static beads 201 times.
    local_mask = np.linalg.norm(network.r0, axis=1) <= cfg.cell_radius + cfg.contact_width + 2.0
    for patch in patches:
        local_mask[network.edges[patch.edge]] = True
    local_beads = np.flatnonzero(local_mask)
    path_length = 0.0

    for step in range(nsteps + 1):
        time = step * cfg.dt
        if step % every == 0 or step == nsteps:
            frames.append(
                _v4_frame(
                    network,
                    center,
                    time,
                    patches,
                    vectors,
                    distance,
                    initial_shell,
                    initial_radial_by_fiber,
                    cell_radius=cfg.cell_radius,
                    requested_force=float(site_force.sum()),
                    bound=state.bound,
                    extension=state.extension,
                    site_force=site_force,
                    actin_speed=actin_speed,
                    substrate_speed=substrate_speed,
                    cumulative_ruptures=state.cumulative_ruptures,
                    cumulative_site_failures=state.cumulative_site_failures,
                )
            )
        if step == nsteps:
            break

        site_force, actin_speed, ruptures, binds, failures = _advance_clutches(
            cfg, state, substrate_speed, step
        )
        event_stamp = (step + 1) * cfg.dt
        for site, clutch in np.argwhere(ruptures):
            event_log.append({"time": event_stamp, "kind": "rupture", "site": int(site), "clutch": int(clutch)})
        for site, clutch in np.argwhere(binds):
            event_log.append({"time": event_stamp, "kind": "bind", "site": int(site), "clutch": int(clutch)})
        for site in np.flatnonzero(failures):
            event_log.append({"time": event_stamp, "kind": "site_failure", "site": int(site)})
            if capture_event and event_time is None and event_stamp >= cfg.minimum_event_time:
                event_time = event_stamp
                event_end = event_stamp + cfg.event_half_window_v4
                event_frames = list(ring)

        active, _, vectors = mapper.map(site_force, center)
        velocity_cell = np.zeros(2, dtype=float)
        if moving:
            # ``vectors`` are cell-on-ECM forces; the cell receives their
            # equal-and-opposite reaction.
            velocity_cell = cell_velocity_from_ecm_forces(vectors, cfg.cell_drag)
            speed = float(np.linalg.norm(velocity_cell))
            if speed > cfg.max_cell_speed:
                velocity_cell *= cfg.max_cell_speed / speed
            delta = cfg.dt * velocity_cell
            center += delta
            path_length += float(np.linalg.norm(delta))

        bead_velocity, _ = stepper.step(active, center, cfg.dt)
        substrate_speed = _relative_substrate_speeds(
            network, bead_velocity, patches, center, velocity_cell
        )

        if np.any(failures):
            patches = _relocate_failed_sites(network, center, patches, failures, cfg)
            mapper.update_patches(patches)
            direct = [int(patch.fiber) for patch in patches]
            distance = graph_distance_from_contact(network, direct)
            for site in np.flatnonzero(failures):
                event_log.append({"time": event_stamp, "kind": "relocate", "site": int(site), "fiber": int(patches[site].fiber)})

        if capture_event and step % event_every == 0:
            detail = _event_snapshot(
                network,
                local_beads,
                center,
                event_stamp,
                patches,
                state,
                site_force,
                ruptures,
                binds,
                substrate_speed,
            )
            if event_time is None:
                ring.append(detail)
            elif event_end is not None and event_stamp <= event_end + 1e-9:
                event_frames.append(detail)

    final_center = np.asarray(center).copy()
    return {
        "config": asdict(cfg),
        "spec": spec,
        "network": network,
        "report": report,
        "mode": "motor-clutch-moving" if moving else "motor-clutch-fixed",
        "moving": bool(moving),
        "frames": frames,
        "event_frames": event_frames,
        "event_time": event_time,
        "event_log": event_log,
        "local_beads": local_beads,
        "patches": patches,
        "graph_distance": distance.copy(),
        "cell_radius_constant": bool(
            all(abs(frame["cell_radius"] - cfg.cell_radius) < 1e-12 for frame in frames)
        ),
        "path_length": float(path_length),
        "net_displacement": float(np.linalg.norm(final_center)),
        "final_center": final_center,
        "max_displacement": float(np.max(np.linalg.norm(network.r - network.r0, axis=1))),
        "site_failures": int(state.cumulative_site_failures),
        "ruptures": int(state.cumulative_ruptures),
    }


def same_geometry_config(cfg: G4V4Config, *, radius: float) -> G4V4Config:
    """Explicit helper for the provisional 8--12 um radius sensitivity test."""

    return replace(cfg, cell_radius=float(radius))


def _small_sample_ci95(values: np.ndarray) -> tuple[float, float]:
    """Two-sided 95% t interval for the predeclared small seed ensemble."""

    values = np.asarray(values, dtype=float)
    if len(values) < 2:
        value = float(values[0]) if len(values) else float("nan")
        return value, value
    critical = {2: 12.706, 3: 4.303, 4: 3.182, 5: 2.776,
                6: 2.571, 7: 2.447, 8: 2.365, 9: 2.306, 10: 2.262}
    t_value = critical.get(len(values), 1.96)
    mean = float(np.mean(values))
    half = float(t_value * np.std(values, ddof=1) / math.sqrt(len(values)))
    return mean - half, mean + half


def run_alignment_ensemble(
    cfg: G4V4Config = G4V4Config(),
    *,
    seeds: tuple[int, ...] = (41, 42, 43, 44, 45),
    duration: float | None = None,
    sample_interval: float | None = None,
) -> dict:
    """Repeat v4-B on independent geometries and test predeclared effects."""

    near_delta: list[float] = []
    one_hop_advantage: list[float] = []
    results: list[dict] = []
    for seed in seeds:
        case_cfg = replace(cfg, seed=int(seed))
        result = run_fixed_force_direction(
            case_cfg,
            geometry="normal",
            duration=duration,
            sample_interval=sample_interval,
        )
        near_delta.append(float(result["final_delta_radial_order_by_shell"][0]))
        graph = result["final_graph_class_metrics"]
        one_hop_advantage.append(
            float(graph["one_hop"]["mean_displacement"] - graph["unconnected"]["mean_displacement"])
        )
        results.append({
            "seed": int(seed),
            "near_delta_radial_order": near_delta[-1],
            "one_hop_minus_unconnected_displacement": one_hop_advantage[-1],
            "contacts": len(result["patches"]),
        })
    near = np.asarray(near_delta)
    hop = np.asarray(one_hop_advantage)
    near_ci = _small_sample_ci95(near)
    hop_ci = _small_sample_ci95(hop)
    return {
        "seeds": [int(seed) for seed in seeds],
        "cases": results,
        "near_delta_mean": float(np.mean(near)),
        "near_delta_ci95": near_ci,
        "near_alignment_excludes_passive_zero": bool(near_ci[0] > 0.0 or near_ci[1] < 0.0),
        "one_hop_advantage_mean": float(np.mean(hop)),
        "one_hop_advantage_ci95": hop_ci,
        "one_hop_exceeds_unconnected": bool(hop_ci[0] > 0.0),
    }


def run_domain_convergence(
    cfg: G4V4Config = G4V4Config(),
    *,
    domain_sizes: tuple[float, ...] = (180.0, 270.0, 360.0),
    duration: float | None = None,
) -> dict:
    """Increase the field while preserving source-fiber areal density."""

    cases = []
    base_density = cfg.n_fibers / cfg.domain_size**2
    for domain in domain_sizes:
        n_fibers = max(20, int(round(base_density * domain**2)))
        case_cfg = replace(cfg, domain_size=float(domain), n_fibers=n_fibers)
        result = run_fixed_force_direction(
            case_cfg,
            duration=duration,
            sample_interval=duration if duration is not None else cfg.fixed_sample_interval,
        )
        cases.append({
            "domain_size": float(domain),
            "n_fibers": int(n_fibers),
            "near_delta_radial_order": float(result["final_delta_radial_order_by_shell"][0]),
            "max_displacement": float(result["max_displacement"]),
        })
    if len(cases) >= 2:
        a = cases[-2]["near_delta_radial_order"]
        b = cases[-1]["near_delta_radial_order"]
        relative = abs(b - a) / max(abs(b), abs(a), 1e-12)
    else:
        relative = float("nan")
    return {
        "cases": cases,
        "last_two_relative_change": float(relative),
        "near_cell_change_below_5_percent": bool(relative < 0.05),
    }


def default_spec(cfg: G4V4Config = G4V4Config()) -> NetworkSpec:
    """Expose the shared-seed G4 v4 source geometry for controlled comparisons."""

    return make_random_void_spec(cfg)
